### ISSUE TITLE
Add To Cart fails - cart does not exist

### ISSUE THREAD

**Issue by oddjob23** [bigcommerce/nextjs-commerce#26]
Hi,

I have cloned a repository and connected my big commerce store with recommended `env` variables. It successfully loads the page and products but there is a bug with add to cart functionality.

First time when clicked, add to cart button,  it seems to be working, it sets the cookie named `cartId` with value of cart entity ID but the cart is empty. The second time when the button is clicked, there is an exception in the function that makes the call to `addCartLineItems` mutation. The error is not properly logged or passed into the components so I have added additional `console.log` for further inspection. Here is the log information:
```{
  error: {
  message: 'Not Found: Cart does not exist',
  path: [ 'cart', 'addCartLineItems' ],
  locations: [ { line: 4, column: 7 } ]
}
```
`cartId` is valid. This error happens on the line `259` in `lib/commerce/bigcommerce/index.ts` `addToCart` function.

I  have noticed that each time my app makes a request a response contains `Set-Cookie` header with cookie names `SHOP_SESSION_TOKEN`  and `SHOP_SESSION_ROTATION_TOKEN` as well. I'm guessing these are the cookies that we should include when making a request to graphql. I tried with `credentials: 'include'` option in `fetch` function, it did not resolve the issue. I'm not sure if it has anything to do with NextJS 13 actions.

Hopefully this will be helpful. Let me know if anything else is needed.

**Comment by BC-krasnoshapka** [comment]
hi @oddjob23 , I'm not able to reproduce this problem on our [demo store](https://next-commerce-v2.vercel.app/). can you reproduce it there? can you please record a video with steps to reproduce? thanks

**Comment by oddjob23** [comment]
Hi @BC-krasnoshapka, I'm sorry that I can't produce a video of the bug but I'll try to give you the steps that I took and got that result.

1. Clone the repository
2. Install dependencies
3. Add environment variables from my own store
4. Start the dev server

Steps to reproduce the bug:

1. Click on the add to cart button
2. Open the cart, cart is empty
3. Click on the add to cart button again
4. Exception happens

I notices that each time a `bigCommerceFetch` function makes the `fetch` call a new `SHOP_SESSION_TOKEN` is returned in the headers so I have resolved this problem by modifying the function like this:

```export async function bigCommerceFetch<T>({
  query,
  variables,
  headers,
  cache = 'force-cache',
}: {
  query: string
  variables?: ExtractVariables<T>
  headers?: HeadersInit
  cache?: RequestCache
}): Promise<{ status: number; body: T; cookie: string } | never> {
  try {
    const result = await fetch(endpoint, {
      method: 'POST',
      headers: {
        Accept: 'application/json',
        Authorization: `Bearer ${process.env.BIGCOMMERCE_CUSTOMER_IMPERSONATION_TOKEN}`,
        'Content-Type': 'application/json',
        Cookie: cookies().toString(),
        ...headers,
      },
      body: JSON.stringify({
        ...(query && { query }),
        ...(variables && { variables }),
      }),
      cache,
    })

    const body = await result.json()

    if (body.errors) {
      throw body.errors[0]
    }

    return {
      status: result.status,
      body,
      cookie: result.headers.get('Set-Cookie') || '',
    }
  } catch (e) {
    if (isVercelCommerceError(e)) {
      throw {
        status: e.status || 500,
        message: e.message,
        query,
      }
    }

    throw {
      error: e,
      query,
    }
  }
}
```
Notice that I'm sending a header `Cookie` and I'm returning that `Set-Cookie` header from response. I'm manually setting in my browser `SHOP_SESSION_TOKEN` and `SHOP_SESSION_REFRESH_TOKEN`. When I have these cookies  included in my requests, everything works perfectly.


I hope this helps.

**Comment by mhuretski** [comment]
same issue for me, I can create cart and get cart `entityId` but when I try to get cart with this `entityId` I'm getting `{ data: { site: { cart: null } } }`

**Comment by prakashramo** [comment]
I am cloning the Next.js Commerce project onto my local system and have entered all my BigCommerce credentials in the .env.local file. The page is rendering correctly, but when I click on 'Add to Cart,' the cart ID is stored in the cookies. I am encountering errors like these.
![Screenshot from 2024-04-23 12-40-39](https://github.com/bigcommerce/nextjs-commerce/assets/163999297/ed05fa95-c8e9-48e7-afee-333447cb0ac9) and when I try to get the cart details by using big commerce graphql API it showing like the cart is empty.

**Comment by oddjob23** [comment]
> I have the same issue both in local and production

Make sure that you are using this endpoint: https://api.bigcommerce.com/stores/{store_hash}/v3/storefront/api-token-customer-impersonation
